// writes the SEAL brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const F = `<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Instrument+Sans:wght@400;500;600&display=swap" rel="stylesheet">`;
const wax = (d) => `<div style="width:${d}px;height:${d}px;border-radius:50%;background:radial-gradient(circle at 38% 32%,#f0c08a,#d9955a 48%,#7a4a22 100%);box-shadow:0 ${d / 10}px ${d / 3}px #000000aa,inset 0 -${d / 18}px ${d / 9}px #00000055,0 0 ${d / 2}px #d9955a44;display:grid;place-items:center;font-family:'Instrument Serif';font-size:${d * .38}px;color:#2a1608;letter-spacing:.1em;position:relative;flex:none"><span style="position:absolute;inset:${d * .125}px;border-radius:50%;border:1px solid #2a160855"></span>S</div>`;
const base = `*{margin:0;box-sizing:border-box}body{background:#0b0a09;color:#f3ede4;font-family:'Instrument Sans',sans-serif;overflow:hidden;position:relative}body::before{content:"";position:absolute;inset:0;background:radial-gradient(55% 45% at 50% -5%,#d9955a22,transparent 70%),radial-gradient(35% 30% at 92% 100%,#d9955a12,transparent 70%)}.se{font-family:'Instrument Serif';font-weight:400}.eye{font-size:24px;letter-spacing:.34em;text-transform:uppercase;color:#d9955a}em{font-style:italic;color:#f0c08a}h1{font-family:'Instrument Serif';font-weight:400;line-height:1;letter-spacing:-.01em}.pad{position:absolute;inset:120px 140px}.foot{position:absolute;left:140px;right:140px;bottom:90px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.14em;color:#a39a8c}.foot b{font-family:'Instrument Serif';font-weight:400;letter-spacing:.24em;font-size:36px;color:#f3ede4;display:flex;align-items:center;gap:20px}.card{background:#141210;border:1px solid #2a2622;padding:48px 46px;position:relative}.card::before{content:"";position:absolute;left:0;right:0;top:0;height:1px;background:linear-gradient(90deg,transparent,#d9955a,transparent)}`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8">${F}<style>body{width:2400px;height:1350px}${base}${css}</style><body>${body}<div class="foot"><b>${wax(44)}SEAL</b><span>sealonrh.xyz · @sealonrh · Robinhood Chain</span></div>`;

fs.writeFileSync(path.join(S, 'seal-pfp.html'), `<!doctype html><meta charset="utf-8">${F}<style>body{width:2000px;height:2000px;display:grid;place-items:center}${base}</style><body>${wax(1240)}`);
fs.writeFileSync(path.join(S, 'seal-banner.html'), `<!doctype html><meta charset="utf-8">${F}<style>body{width:3000px;height:1000px}${base}h1{position:absolute;left:190px;top:230px;font-size:190px}p{position:absolute;left:198px;bottom:150px;font-size:42px;letter-spacing:.14em;color:#a39a8c}.w{position:absolute;right:300px;top:190px}</style><body><h1>Pay people.<br>Show <em>no one.</em></h1><p>SEAL · sUSD · private payroll on Robinhood Chain · sealonrh.xyz</p><div class="w">${wax(620)}</div>`);

fs.writeFileSync(path.join(S, 'seal-keyart.html'), page(`<div class="pad"><div class="eye">private payroll · Robinhood Chain</div><h1 style="font-size:180px;margin-top:60px">Pay people.<br>Show <em>no one.</em></h1><p style="font-size:42px;color:#a39a8c;max-width:1250px;margin-top:70px;line-height:1.6">Stream salaries, send invoices, hand out signed receipts. <b style="color:#f3ede4;font-weight:500">No sender, no recipient, no amount on the ledger.</b></p></div><div style="position:absolute;right:220px;top:330px">${wax(560)}</div>`));

const steps = [['01', 'Stream', 'Pick an address, an amount, a period and a count. SEAL pays it every period as a sealed send, on time, with a signed receipt.'], ['02', 'Invoice', 'Ask for sUSD as a link. Whoever opens it pays from their sealed balance into yours. The payer is never named.'], ['03', 'Prove it', 'Every payment issues a sealed receipt: id, amount, time, signature. Anyone verifies it at /verify without learning who paid.']];
fs.writeFileSync(path.join(S, 'seal-howitworks.html'), page(`<div class="pad"><div class="eye">how it works</div><h1 style="font-size:110px;margin-top:40px">Three moves. <em>No names.</em></h1><div class="g">${steps.map((s) => `<div class="card"><i>${s[0]}</i><h2>${s[1]}</h2><p>${s[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:34px;margin-top:80px}.card{height:560px}.card i{font-style:normal;font-size:24px;letter-spacing:.3em;color:#d9955a}.card h2{font-family:'Instrument Serif';font-weight:400;font-size:74px;margin:34px 0 26px}.card p{font-size:31px;line-height:1.6;color:#a39a8c}`));

fs.writeFileSync(path.join(S, 'seal-receipt.html'), page(`<div class="pad"><div class="eye">sealed receipt</div><h1 style="font-size:110px;margin-top:40px">Proof it happened. <em>Nothing else.</em></h1><div class="rc card"><div class="ok">seal verified · HMAC-SHA256</div><div class="kv"><span>amount</span><b class="se" style="font-size:72px">4,200.00 sUSD</b></div><div class="kv"><span>kind</span><b>stream · monthly</b></div><div class="kv"><span>paid at</span><b>Tue, 22 Sep 2026 14:00:00 GMT</b></div><div class="kv"><span>receipt</span><b>8xQV7MvwVST</b></div><div class="kv"><span>sender</span><b class="nd">not disclosed</b></div><div class="kv"><span>recipient</span><b class="nd">not disclosed</b></div></div></div>`, `.rc{margin-top:60px;width:1560px;padding:52px 60px}.ok{display:inline-flex;align-items:center;gap:14px;font-size:22px;letter-spacing:.24em;text-transform:uppercase;padding:14px 24px;border:1px solid #d9955a;color:#f0c08a;margin-bottom:20px}.ok::before{content:"";width:16px;height:16px;border-radius:50%;background:#d9955a;box-shadow:0 0 18px #d9955a}.kv{display:flex;justify-content:space-between;align-items:baseline;gap:20px;padding:18px 0;border-bottom:1px solid #2a2622;font-size:34px}.kv span{color:#a39a8c}.kv b{font-weight:500}.kv .nd{color:#f0c08a;font-style:italic;font-family:'Instrument Serif';font-weight:400;font-size:40px}`));

const feats = [['Streams', 'Salary, rent, retainers on a schedule, under seal. Pauses if dry, resumes on top-up.'], ['Invoices', 'Get paid by a link. The payer is never named. One payment per invoice.'], ['Sealed receipts', 'Signed proof of payment with no sender or recipient. Verify at /verify.'], ['Quiet Yield', '40% of every fee streams to sealed sUSD holders. No staking, no lock.'], ['Ledger key', 'A read-only view key for your accountant. It can never spend.'], ['Envelopes', 'Send sealed dollars as a one-time link. No address needed.'], ['Blind Desk', 'Treasury exposure to tokenized stocks, ticker and size sealed.'], ['Real USDG', 'Deposits verified on Robinhood Chain. Withdrawals from a cold wallet.']];
fs.writeFileSync(path.join(S, 'seal-features.html'), page(`<div class="pad"><div class="eye">the desk</div><h1 style="font-size:100px;margin-top:36px">Everything a private treasury <em>needs.</em></h1><div class="g">${feats.map((f, i) => `<div class="f"><i>0${i + 1}</i><h2>${f[0]}</h2><p>${f[1]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:0 50px;margin-top:70px}.f{border-top:1px solid #2a2622;padding:32px 0 44px;height:330px}.f i{font-style:normal;font-size:20px;letter-spacing:.3em;color:#d9955a}.f h2{font-family:'Instrument Serif';font-weight:400;font-size:52px;margin:14px 0 12px}.f p{font-size:27px;line-height:1.55;color:#a39a8c}`));
console.log('seal kit scenes written');
